### ISSUE TITLE
Kotlin 1.3.40

### ISSUE THREAD

**Issue by Zomis** [Lewik/klog#1]
Kotlin 1.3.40 was released a little while ago. Any plans for making a 1.3.40 release?

**Comment by Lewik** [comment]
Yes. Sorry for the delay. Feel free to bump me or make a PR by yourself. Just look at the latest commits to find what to change. CI server (JitPack) will automatically build files. Could you try to get 1.3.40 now? @Zomis

**Comment by Lewik** [comment]
@Zomis 1.3.41 updated
